name: flutter_local_ai
description: A Flutter package that wraps Android ML Kit GenAI and Apple Foundation Models APIs (iOS and macOS) for local AI inference.
version: 0.0.1-dev.6
homepage: https://github.com/kekko7072/flutter_local_ai

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.vezz.flutter_local_ai
        pluginClass: FlutterLocalAiPlugin
      ios:
        pluginClass: FlutterLocalAiPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterLocalAiPlugin
        sharedDarwinSource: true
